// <auto-generated />
using FitnessTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessTracker.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MuscleGroup = "Legs",
                            Name = "Squat",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 2,
                            MuscleGroup = "Chest",
                            Name = "Bench Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 3,
                            MuscleGroup = "Back",
                            Name = "Barbell Row",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 4,
                            MuscleGroup = "Shoulders",
                            Name = "Overhead Press",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 5,
                            MuscleGroup = "Legs",
                            Name = "Romanian Deadlift",
                            Type = "Compound"
                        },
                        new
                        {
                            Id = 6,
                            MuscleGroup = "Back",
                            Name = "Deadlift",
                            Type = "Compound"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
